IF(DNS-SD_LIBRARIES)
   SET(DNS-SD_FIND_QUIETLY TRUE)
ENDIF(DNS-SD_LIBRARIES)

FIND_PATH(DNS-SD_INCLUDE_DIR dns_sd.h PATHS)

FIND_LIBRARY(DNS-SD_LIBRARIES NAMES dns_sd)

IF(DNS-SD_INCLUDE_DIR AND DNS-SD_LIBRARIES)
   SET(DNS-SD_FOUND TRUE)
ELSE(DNS-SD_INCLUDE_DIR AND DNS-SD_LIBRARIES)
   SET(DNS-SD_FOUND FALSE)
ENDIF (DNS-SD_INCLUDE_DIR AND DNS-SD_LIBRARIES)

IF(DNS-SD_FOUND)
   IF(NOT DNS-SD_FIND_QUIETLY)
      MESSAGE(STATUS "Found DNS-SD: ${DNS-SD_LIBRARIES}")
   ENDIF(NOT DNS-SD_FIND_QUIETLY)
ELSE(DNS-SD_FOUND)
   IF(DNS-SD_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could NOT find DNS-SD")
   ENDIF(DNS-SD_FIND_REQUIRED)
ENDIF(DNS-SD_FOUND)

MARK_AS_ADVANCED(DNS-SD_INCLUDE_DIR DNS-SD_LIBRARIES)

