IF(AVAHI-CLIENT_LIBRARIES)
   SET(Avahi-Client_FIND_QUIETLY TRUE)
ENDIF(AVAHI-CLIENT_LIBRARIES)

FIND_PACKAGE(Avahi-Common REQUIRED)

FIND_PATH(AVAHI-CLIENT_INCLUDE_DIR 
   avahi-client/client.h
   avahi-client/lookup.h
   avahi-client/publish.h
   PATHS)

FIND_LIBRARY(AVAHI-CLIENT_LIBRARIES NAMES avahi-client)

IF(AVAHI-CLIENT_INCLUDE_DIR AND AVAHI-CLIENT_LIBRARIES)
   SET(AVAHI-CLIENT_FOUND TRUE)
ELSE(AVAHI-CLIENT_INCLUDE_DIR AND AVAHI-CLIENT_LIBRARIES)
   SET(AVAHI-CLIENT_FOUND FALSE)
ENDIF(AVAHI-CLIENT_INCLUDE_DIR AND AVAHI-CLIENT_LIBRARIES)

IF(AVAHI-CLIENT_FOUND)
   IF(NOT Avahi-Client_FIND_QUIETLY)
      MESSAGE(STATUS "Found Avahi-Client: ${AVAHI-CLIENT_LIBRARIES}")
   ENDIF(NOT Avahi-Client_FIND_QUIETLY)
ELSE(AVAHI-CLIENT_FOUND)
   IF(Avahi-Client_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could NOT find Avahi-Client")
   ENDIF(Avahi-Client_FIND_REQUIRED)
ENDIF(AVAHI-CLIENT_FOUND)

MARK_AS_ADVANCED(AVAHI-CLIENT_INCLUDE_DIR AVAHI-CLIENT_LIBRARIES)

