IF(ICONV_LIBRARIES)
   SET(Iconv_FIND_QUIETLY TRUE)
ENDIF(ICONV_LIBRARIES)

FIND_PATH(ICONV_INCLUDE_DIR iconv.h PATHS)

# GNU/Linux's libc (glibc) includes iconv internaly, normaly it's a separate lib
IF(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
  FIND_LIBRARY(ICONV_LIBRARIES NAMES c)
ELSE(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
  FIND_LIBRARY(ICONV_LIBRARIES NAMES iconv)
ENDIF(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")

IF(ICONV_INCLUDE_DIR AND ICONV_LIBRARIES)
   SET(ICONV_FOUND TRUE)
ELSE(ICONV_INCLUDE_DIR AND ICONV_LIBRARIES)
   SET(ICONV_FOUND FALSE)
ENDIF (ICONV_INCLUDE_DIR AND ICONV_LIBRARIES)

IF(ICONV_FOUND)
   IF(NOT Iconv_FIND_QUIETLY)
      MESSAGE(STATUS "Found iconv: ${ICONV_LIBRARIES}")
   ENDIF(NOT Iconv_FIND_QUIETLY)
ELSE(ICONV_FOUND)
   IF(Iconv_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could NOT find iconv")
   ENDIF(Iconv_FIND_REQUIRED)
ENDIF(ICONV_FOUND)

MARK_AS_ADVANCED(ICONV_INCLUDE_DIR ICONV_LIBRARIES)

