CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

# --- Package generation
SET(BUILD_RPM no CACHE BOOL "Build an RPM package file (need rpmtools)")
SET(BUILD_DEB no CACHE BOOL "Build an deb package file (need dpkg)")


INCLUDE(InstallRequiredSystemLibraries)
SET(CPACK_PACKAGE_NAME "omiscid")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OMiSCID Middleware")
SET(CPACK_PACKAGE_VENDOR "INRIA")
STRING(REGEX REPLACE "^([0-9]+)\\.[0-9]+\\.[0-9]+" "\\1" CPACK_PACKAGE_VERSION_MAJOR "${OMISCID_VERSION}")
STRING(REGEX REPLACE "^[0-9]+\\.([0-9])+\\.[0-9]+" "\\1" CPACK_PACKAGE_VERSION_MINOR "${OMISCID_VERSION}")
STRING(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+)" "\\1" CPACK_PACKAGE_VERSION_PATCH "${OMISCID_VERSION}")
SET(CPACK_SET_DESTDIR "ON")
SET(CPACK_PACKAGE_CONTACT "omiscid@gforge.inria.fr")

# -- RPM package
IF(BUILD_RPM)
    SET(CPACK_RPM_PACKAGE_ARCHITECTURE noarch)
    SET(CPACK_RPM_PACKAGE_RELEASE 1)
    SET(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
    SET(CPACK_RPM_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION_SUMMARY})
    SET(CPACK_RPM_PACKAGE_REQUIRES "cmake >= 2.6")
    SET(CPACK_GENERATOR "RPM;${CPACK_GENERATOR}")
ENDIF(BUILD_RPM)

# -- Debian package
IF(BUILD_DEB) 
#    SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE all)
    SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")
    SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "omiscid@gforge.inria.fr")
    SET(CPACK_GENERATOR "DEB;${CPACK_GENERATOR}")
    SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libxml2-dev, libboost1.40-dev")
ENDIF(BUILD_DEB)

INCLUDE(CPack)
